### ISSUE TITLE
DoctrineMongoODMModule 3.0 Upgrade

### ISSUE THREAD

**Issue by kilip** [cross-solution/YAWIK#599] opened 2020-12-04 08:41 UTC
Need to verify that GridFS upload and read is working:

- [x]  Fix Auth upload error
- [x]  Fix Application upload error
- [x] Fix CV upload errror
- [x] Fix Organization upload error
- [x] Integrate ```/bin/console migrate``` command during composer post install/update.
- [x] Store ```/bin/console migrate``` status into database, so it will not running twice on successful command.
- [x] Ensure DoctrineMongoODMModule\Proxy dir exists
- [x] Fix install error during composer post script

This issue is related with #591

**Comment by cbleek** [comment] 2020-12-07 15:29
@TiSiE FYI

if i run phpunit, two tests are failing. Propably because there are two tasks open.

1) CoreTest\Functional\Manager\FileManagerFunctionalTest::testAddImage
ProxyManager\Exception\InvalidProxyDirectoryException: Provided directory "/home/cbleek/kilip-yawik/var/cache/DoctrineMongoODMModule/Proxy" does not exist

2) OrganizationsTest\Functional\OrganizationFunctionalTest::testCreateOrganization
ProxyManager\Exception\InvalidProxyDirectoryException: Provided directory "/home/cbleek/kilip-yawik/var/cache/DoctrineMongoODMModule/Proxy" does not exist

**Comment by TiSiE** [comment] 2020-12-09 10:35
@kilip 
For the last point see my comment here: https://github.com/cross-solution/YAWIK/issues/591#issuecomment-741676465

I will look into it and eventually commit in your PR

**Comment by TiSiE** [comment] 2020-12-09 15:46
@cbleek @kilip: see https://github.com/cross-solution/YAWIK/issues/591#issuecomment-741858869

**Comment by cbleek** [comment] 2020-12-09 17:05
After commeting the folloging lines, composer install works as expected. Syslinks are created and the following npm process builds the js and css files

Let's comment the lines for now.

https://github.com/yawik/composer-plugin/blob/master/src/AssetsInstaller.php#L123

https://github.com/yawik/composer-plugin/blob/master/src/AssetsInstaller.php#L164-L180

**Comment by cbleek** [comment] 2020-12-15 08:16
@kilip can you please take the time to wrap up the last few things? The thing with the "Fix install error during composer post script" has been done by Mathias.

**Comment by cbleek** [comment] 2020-12-18 11:26
great. All tests are running now. Keep going.

**Comment by cbleek** [comment] 2020-12-18 22:17
have seen that all the tasks are checked off.

What do I have to do now?

merge  https://github.com/cross-solution/YAWIK/pull/597 into master, run`bin/console migrate` and test if everythings working?

**Comment by kilip** [comment] 2020-12-19 05:35
@cbleek just merge this pull into odm-module3 branch (i have make #591 pull to merge into odm-module3 branch).

We need to be sure that this upgrade is error free before we merge it into master branch

**Comment by cbleek** [comment] 2020-12-19 17:02
I've nerged it into odm-moduke3 and executed `bin/console migrate`. 

I get to following eror

`[2020-12-19 12-03-26] Laminas\ServiceManager\Exception\ServiceNotCreatedException: Service with name "Core/DocumentManager" could not be created. Reason: Index with name: contact.image_1 already exists with a different name #85 in /home/cbleek/yawik/vendor/laminas/laminas-servicemanager/src/ServiceManager.php:772 caused by MongoDB\Driver\Exception\CommandException: Index with name: contact.image_1 already exists with a different name #85 in /home/cbleek/yawik/vendor/mongodb/mongodb/src/Operation/CreateIndexes.php:227  @  http://10.10.1.28:8080/favicon.ico  @@  exception--2020-12-19--10-02--e0f31a11d0.html`

[exception--2020-12-19--10-03--ab7b1bf4ce.txt](https://github.com/cross-solution/YAWIK/files/5719814/exception--2020-12-19--10-03--ab7b1bf4ce.txt)

To make sure all indexes are recreated, I've recreated the databse with mongodump/mongorestore .  I've found an Index with a  name`contact.image_1` in the cvs collection.

@kilip Do you have an Idea?

**Comment by cbleek** [comment] 2020-12-19 17:42
This error does not occure, if I use our YawikDemo DB.

I'll try to update the demo.

**Comment by cbleek** [comment] 2020-12-21 20:36
let'S close this. We'll create single issues in https://github.com/cross-solution/YAWIK/milestone/31

**Closed by cbleek** 2020-12-21 20:36 UTC
