### ISSUE TITLE
ApplyURLHelper breaks external link

### ISSUE THREAD

**Issue by mbo-s** [cross-solution/YAWIK#481] opened 2018-09-06 15:41 UTC
https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/src/Jobs/View/Helper/ApplyUrl.php#L111-L113

there should be an extra check for an external URL like in 
https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/src/Jobs/View/Helper/JobUrl.php#L112-L114

otherwise it breaks the link e.g. in https://github.com/cross-solution/YAWIK/blob/develop/module/Jobs/view/jobs/export/feed.xml.phtml#L76

e.g. an external applylink https://example.com/apply results in https://yawik.org/demo/https://example.com/apply

**Comment by cbleek** [comment] 2018-09-08 16:32
I cannot reproduce the problem. I've set an external UL

https://yawik.org/demo/en/jobs/view?id=5b2a56360acec36513ee86fa

So I close this issue. Reopen it, if you think I'm wrong.

**Comment by mbo-s** [comment] 2018-09-08 17:36
It is still broken if you try to generate an absolute link

https://yawik.org/demo/de/export/xml?page=6

`<job id="5b2a56360acec36513ee86fa">`
`<title>Schreiner</title>`
`<location>Dortmund</location>`
`<datePublishStart>2018-06-20T15:41:48+02:00</datePublishStart>`
`<datePublishEnd/>`
`<dateModified>2018-09-08T18:27:45+02:00</dateModified>`
`<url type="application">https://yawik.orghttps://example.com/apply</url>`

expected value would be
`<url type="application">https://example.com/apply</url>`

**Closed** 2019-01-16 16:02 UTC
Labels: Jobs, bug, confirmed
